/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // osahou brand tokens — CSS変数経由で参照
        'primary':                    'var(--color-primary)',
        'primary-container':          'var(--color-primary-container)',
        'on-primary':                 'var(--color-on-primary)',
        'surface':                    'var(--color-surface)',
        'surface-container-lowest':   'var(--color-surface-container-lowest)',
        'surface-container-low':      'var(--color-surface-container-low)',
        'surface-container':          'var(--color-surface-container)',
        'surface-container-high':     'var(--color-surface-container-high)',
        'surface-container-highest':  'var(--color-surface-container-highest)',
        'on-surface':                 'var(--color-on-surface)',
        'on-surface-variant':         'var(--color-on-surface-variant)',
        'outline':                    'var(--color-outline)',
        'outline-variant':            'var(--color-outline-variant)',
        'error':                      'var(--color-error)',
        'error-container':            'var(--color-error-container)',
        'on-error-container':         'var(--color-on-error-container)',
        'success':                    'var(--color-success)',
        'success-container':          'var(--color-success-container)',
        'on-success-container':       'var(--color-on-success-container)',
        'warning':                    'var(--color-warning)',
        'warning-container':          'var(--color-warning-container)',
        'on-warning-container':       'var(--color-on-warning-container)',
        'secondary':                  'var(--color-secondary)',
        'passport-navy':              'var(--passport-navy)',
        'passport-gold':              'var(--passport-gold)',
        'passport-cream':             'var(--passport-cream)',
        'passport-stamp':             'var(--passport-stamp)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      spacing: {
        '1':  'var(--space-1)',
        '2':  'var(--space-2)',
        '3':  'var(--space-3)',
        '4':  'var(--space-4)',
        '5':  'var(--space-5)',
        '6':  'var(--space-6)',
        '8':  'var(--space-8)',
        '10': 'var(--space-10)',
        '12': 'var(--space-12)',
        '16': 'var(--space-16)',
        '24': 'var(--space-24)',
      },
      borderRadius: {
        'none': 'var(--radius-none)',
        'sm':   'var(--radius-sm)',
        'md':   'var(--radius-md)',
        'lg':   'var(--radius-lg)',
        'xl':   'var(--radius-xl)',
        'full': 'var(--radius-full)',
      },
      boxShadow: {
        'sm':      'var(--shadow-sm)',
        'md':      'var(--shadow-md)',
        'lg':      'var(--shadow-lg)',
        'xl':      'var(--shadow-xl)',
        'sm-cool': 'var(--shadow-sm-cool)',
        'md-cool': 'var(--shadow-md-cool)',
      },
      transitionDuration: {
        'fast':   'var(--duration-fast)',
        'normal': 'var(--duration-normal)',
        'slow':   'var(--duration-slow)',
      },
      transitionTimingFunction: {
        'out':    'var(--ease-out)',
        'in':     'var(--ease-in)',
        'in-out': 'var(--ease-in-out)',
      },
      zIndex: {
        'dropdown': 'var(--layer-dropdown)',
        'sticky':   'var(--layer-sticky)',
        'overlay':  'var(--layer-overlay)',
        'modal':    'var(--layer-modal)',
        'toast':    'var(--layer-toast)',
        'tooltip':  'var(--layer-tooltip)',
      },
    },
  },
  plugins: [],
}
